# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: system-info
  description: A repo to store system info
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master

# See https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator for available options
collaborators:
  - username: ryanschuhler
    permission: admin

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
teams:
  - name: liferay/is-department
    permission: pull
