# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: system-info
  description: A repo to store system info
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master

# See https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator for available options
collaborators:
  - username: ryanschuhler
    permission: admin

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
teams:
  - name: liferay/is-department
    # The permission to grant the team. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
    # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
    # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
    permission: pull
